version: '3'
services:
  app:
    container_name: booking-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh start.sh
    restart: always
    env_file:
       - ".env"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 127.0.0.1:${SERVICE_PORT}:8765
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1
    container_name: postgres-booking
    hostname: postgres
    env_file:
      - ".env"
    ports:
      - 127.0.0.1:${DATABASE_PORT}:5432/tcp
    environment:
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
    volumes:
      - "./service/postgresql:/var/lib/postgresql/data"
    restart: unless-stopped