# Generated by Django 5.0.2 on 2024-03-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='sub',
            new_name='subscriber',
        ),
    ]
