# Generated by Django 5.0.2 on 2024-02-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
